### ISSUE TITLE
🔐 Implement Configuration and Authentication for MCP Server

### ISSUE THREAD

**Issue by dietrichson** [chi2labs/moodleR#21]
## Description
Implement secure configuration management and authentication for the moodleR MCP server.

### Configuration Management
- [ ] Design configuration schema for MCP server
- [ ] Support multiple configuration sources:
  - Environment variables
  - Configuration files (YAML/JSON)
  - Command-line arguments
- [ ] Implement configuration validation
- [ ] Create configuration migration tools

### Authentication Implementation
- [ ] Database credential management
  - Secure storage of Moodle DB credentials
  - Support for credential rotation
  - Multiple database profiles
  
- [ ] MCP client authentication (if needed)
  - API key authentication
  - Token-based authentication
  - Rate limiting per client

### Security Features
- [ ] Implement secure credential storage
  - Encryption at rest
  - Environment variable support
  - Integration with secret managers (optional)
  
- [ ] Add audit logging
  - Log all authentication attempts
  - Track data access patterns
  - Configurable log retention

## Configuration Schema

```yaml
mcp_server:
  host: "0.0.0.0"
  port: 8080
  transport: "http"  # or "stdio"
  
authentication:
  enabled: false
  type: "api_key"  # or "token"
  
rate_limiting:
  enabled: true
  requests_per_minute: 60
  
moodle_connections:
  default:
    host: "${MOODLE_DB_HOST}"
    port: 3306
    database: "${MOODLE_DB_NAME}"
    username: "${MOODLE_DB_USER}"
    password: "${MOODLE_DB_PASSWORD}"
    driver: "mariadb"
    
  production:
    # Additional connection profile
    
cache:
  directory: "./moodle_cache"
  filename: "cache.sqlite"
  auto_refresh: true
  refresh_interval: 3600  # seconds
  
logging:
  level: "info"
  format: "json"
  output: "stdout"
  audit_log: "./logs/audit.log"
```

## Security Considerations
- Never log sensitive credentials
- Support credential rotation without restart
- Implement connection pooling with security
- Add SQL injection prevention
- Support read-only database users

## Testing
- [ ] Test configuration loading from all sources
- [ ] Test credential security (no leaks in logs)
- [ ] Test authentication flows
- [ ] Test rate limiting
- [ ] Security audit of implementation

## Documentation
- [ ] Configuration guide
- [ ] Security best practices
- [ ] Deployment examples
- [ ] Troubleshooting guide
