### ISSUE TITLE
📦 Create Deployment and Packaging Solution

### ISSUE THREAD

**Issue by dietrichson** [chi2labs/moodleR#23]
## Description
Develop deployment and packaging solutions for the moodleR MCP server to support various deployment scenarios.

### Local Development
- [ ] Development setup script
- [ ] Docker Compose configuration
- [ ] Hot reload support
- [ ] Debug mode configuration

### Standalone Server
- [ ] Systemd service files
- [ ] Init.d scripts
- [ ] Windows service wrapper
- [ ] macOS LaunchAgent

### Containerized Deployment
- [ ] Multi-stage Dockerfile
- [ ] Docker image optimization
- [ ] Kubernetes manifests
- [ ] Helm chart (optional)

### Cloud Deployment
- [ ] AWS Lambda deployment (if applicable)
- [ ] Google Cloud Run configuration
- [ ] Azure Functions setup
- [ ] Heroku deployment files

### Package Formats
- [ ] R package with MCP server included
- [ ] Standalone executable (R + dependencies)
- [ ] Python wheel (if Python bridge)
- [ ] NPM package (if Node.js bridge)
- [ ] System packages (deb, rpm)

### Distribution Channels
- [ ] CRAN submission (R package)
- [ ] GitHub Releases
- [ ] Docker Hub
- [ ] Package registries (PyPI, npm)

### Claude Desktop Integration
```json
{
  "mcpServers": {
    "moodler": {
      "command": "moodler-mcp",
      "args": ["--config", "~/.moodler/config.yml"],
      "env": {
        "MOODLER_CACHE_DIR": "~/.moodler/cache"
      }
    }
  }
}
```

### Docker Compose Example
```yaml
version: '3.8'
services:
  moodler-mcp:
    image: chi2labs/moodler-mcp:latest
    ports:
      - "8080:8080"
    environment:
      - MOODLE_DB_HOST=db
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodle
      - MOODLE_DB_PASSWORD=secret
    volumes:
      - ./cache:/app/cache
      - ./config:/app/config
```

### One-line Installers
- [ ] Shell script for Unix systems
- [ ] PowerShell script for Windows
- [ ] Homebrew formula (macOS)
- [ ] Snap package (Linux)

### Example Install Script
```bash
curl -fsSL https://get.moodler-mcp.io | bash
```

## Health Monitoring
- [ ] Health check endpoints
- [ ] Prometheus metrics
- [ ] Logging aggregation support
- [ ] Performance monitoring

## Update Mechanism
- [ ] Version checking
- [ ] Auto-update capability
- [ ] Rollback support
- [ ] Update notifications

## Security Hardening
- [ ] Non-root container images
- [ ] Security scanning in CI/CD
- [ ] SBOM generation
- [ ] Vulnerability reporting

## Testing
- [ ] Installation testing matrix
- [ ] Upgrade/downgrade testing
- [ ] Cross-platform testing
- [ ] Performance benchmarks

## Documentation
- [ ] Installation guide per platform
- [ ] Deployment best practices
- [ ] Troubleshooting guide
- [ ] Migration guide
